config/routes.rb
ToDo::Application.routes.draw do

  # resources :tasks
  
  get    '/',           controller: 'tasks', action: 'index', as: :tasks
  post   '/',           controller: 'tasks', action: 'create' 
  
  get    '/:id/edit',   controller: 'tasks', action: 'edit',  as: :edit_task
  get    '/:id',        controller: 'tasks', action: 'show', as: :task
  put    '/:id',        controller: 'tasks', action: 'update' 
  
  delete '/:id',        controller: 'tasks', action: 'delete'

end

app/models/task.rb
class Task < ActiveRecord::Base
  attr_accessible :name
  validates :name, :presence => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  def index
    @tasks = Task.all
    @task = Task.new   
  end
  
  def new
  end

  def create
    @tasks = Task.all
    @task = Task.new(params[:task])
    if @task.save
      redirect_to tasks_url, notice: "Ha ha! Make the monkey #{@task.name}. Good one!"
    else
      render "index"
      flash[:alert] = "not saved"
    end
  end

  def edit
    @task = Task.find(params[:id])
  end
  
  def show
    
  end

  def update
    @task = Task.find(params[:id])
    if @task.update_attributes(params[:task])
      redirect_to tasks_url
    else
      render "index"
    end 
  end

  def delete
    @task = Task.find(params[:id])
    @task.delete
    redirect_to tasks_url
    
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ToDo</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <link href='http://fonts.googleapis.com/css?family=Glegoo|Patua+One' rel='stylesheet' type='text/css'>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div id="notices">
  <% flash.each do |key, msg| %>
  <%= content_tag :div, msg, id: key %>
  <% end %>
  </div>
<%= yield %>

</body>
</html>

app/views/shared/_notice.html.erb
<div>
  <%= flash[:notice] %>
</div>

<div>
    <%= flash[:alert] %>
</div>

app/views/tasks/_form.html.erb
<%= form_for @task do |task| %> 
<% if @task.errors.any? %>
<%= @task.errors.full_messages.to_sentence %>
<% end %>

<%= task.text_field :name %>
<%= task.submit "Monkey Do", class: "button" %>
<% end %>

app/views/tasks/edit.html.erb
<h1>""<%= @task.name %>"" is lame. Let's change it!</h1>
<%= render 'form' %>

app/views/tasks/index.html.erb
<h1>Things to do with a pet monkey</h1>
<h2>Created by <a href="http://www.twitter.com/dmwoodall">Dave Woodall</a> at <a href="http://www.codeacademy.org">Code Academy</a> for people who are thinking of getting a pet monkey. <br>Built using Ruby on Rails.</h2>
<div id="form">
<%= render 'form' %>
</div>
<% @tasks.each do |task| %>
  <ul>
    <li><%= task.name %> <div id="links"> 
      <%= link_to "edit", edit_task_url(task) %>  
      <%= link_to "delete", task_url(task), method: :delete, confirm: "You don't want the monkey to #{task.name}?" %></div>
    </li>
  </ul>
<% end %>